Moved all text into language files.
getcandy/getcandy pull request #230
Opened 2022-03-18 17:23 UTC by Gmanprodev

Moved all text into language files for translation purposes.

2022-03-25 10:19 UTC, alecritson commented on packages/admin/resources/lang/en/partials.php
> +    'products.associations.alfra_piccolo' => 'Alfra Piccolo 38\/50B Magnetic Drilling Machine 240V (mag drill)',
How comes a product name is in the translations?

2022-03-25 10:23 UTC, alecritson commented on packages/admin/resources/lang/en/components.php
> +    'products.index.you_have_selected' => 'You have selected',
When writing translations that have dynamic values, you can add placeholders so:

```php
'products.index.selected_products' => 'You have selected :count products'
```

Then in the translation you would do:

```php
__('adminhub::translation....', [
    'count' => 123,
]);
```

We should avoid breaking up sentences where possible as the structure will change depending on the language.

2022-03-25 10:25 UTC, Gmanprodev commented on packages/admin/resources/lang/en/partials.php
> +    'products.associations.alfra_piccolo' => 'Alfra Piccolo 38\/50B Magnetic Drilling Machine 240V (mag drill)',
It was text in a blade file and assumed it should be moved too.

2022-03-25 10:26 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
> +    'products.index.you_have_selected' => 'You have selected',
Ah - ok, thanks for the feedback on that.

2022-03-25 10:31 UTC, alecritson commented on packages/admin/resources/lang/en/partials.php
> +    'products.associations.alfra_piccolo' => 'Alfra Piccolo 38\/50B Magnetic Drilling Machine 240V (mag drill)',
Found the file, it was old code so it's been removed on the `main` branch. Just needs removing from this one.

2022-03-29 13:10 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
> +    'products.index.you_have_selected' => 'You have selected',
Done.

2022-03-29 13:10 UTC, Gmanprodev commented on packages/admin/resources/lang/en/partials.php
> +    'products.associations.alfra_piccolo' => 'Alfra Piccolo 38\/50B Magnetic Drilling Machine 240V (mag drill)',
Done.

2022-03-29 13:33 UTC, alecritson requested changes
There's a few partial sentences left over and it looks like there's some Meilisearch stuff that's been committed, this needs removing.

2022-03-29 13:33 UTC, alecritson commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
This looks like a partial translation that needs combining with a placeholder?

2022-03-29 13:33 UTC, alecritson commented on packages/admin/resources/lang/en/auth.php
> +    'gc-reset-password.title'   => 'GetCandy - Reset Password',
I don't think "GetCandy" should be in here since we don't want it translated.

2022-03-29 13:33 UTC, alecritson commented on packages/admin/resources/lang/en/global.php
> +    'reach_out'               => 'Feel free to reach out on our',
Partial sentence, does it need combing?

2022-03-29 13:33 UTC, alecritson commented on packages/admin/resources/lang/en/partials.php
> +    'image-manager.drag_and_drop'                    => 'or drag and drop',
Partial sentence.

2022-03-29 14:47 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
You mean the name of the placeholder doesn't match what I have in the blade file?

2022-03-29 14:54 UTC, Gmanprodev commented on packages/admin/resources/lang/en/auth.php
> +    'gc-reset-password.title'   => 'GetCandy - Reset Password',
done.

2022-03-29 15:51 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
Done.

2022-03-29 15:54 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
When you say Meillisearch stuff, do you mean this......

![image](https://user-images.githubusercontent.com/53705684/160653711-8211f960-3178-4450-9ecf-66f2e626c12e.png)

2022-03-29 16:01 UTC, Gmanprodev commented on packages/admin/resources/lang/en/global.php
> +    'reach_out'               => 'Feel free to reach out on our',
So the sentence reads "Feel free to reach out on our Discord server for updates". 
I've separated this sentence as the Discord Server text is a link. Let me know how you'd prefer me to proceed on this one.

2022-03-30 08:01 UTC, alecritson commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/1488016/160782023-8c70bb0e-c032-483e-bf6f-7c1fddb315c1.png">

2022-03-30 08:28 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
Remove all the files that are shown here or just the 2 with the green changes (version & instance-uid) ?

2022-03-30 08:44 UTC, alecritson commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
Remove anything like `data.ms` as that looks like Meilisearch

2022-03-30 09:22 UTC, Gmanprodev commented on packages/admin/resources/lang/en/components.php
>      'products.index.want_to_select_all' => 'products, do you want to select all',
Done.

2022-03-30 09:23 UTC, Gmanprodev commented on packages/admin/resources/lang/en/global.php
> +    'reach_out'               => 'Feel free to reach out on our',
What are your thoughts on this ?

2022-03-30 09:36 UTC, alecritson commented on packages/admin/resources/lang/en/global.php
> +    'reach_out'               => 'Feel free to reach out on our',
We don't really want all that link stuff in the translation file 🤔 maybe leave as is for now.

2022-03-30 09:37 UTC, Gmanprodev commented on packages/admin/resources/lang/en/global.php
> +    'reach_out'               => 'Feel free to reach out on our',
ok - cool.
I'll commit the changes now and let me know if anything else comes up that you want me to look at.

2022-03-31 09:30 UTC, merged