Feat/order notifications
getcandy/getcandy pull request #333
Opened 2022-06-24 13:53 UTC by alecritson

Initial work on bringing in order notifications to the hub

2022-07-15 13:34 UTC, glennjacobs commented
Needs a change log entry and example mailable to show how content is injected.

2022-07-26 16:39 UTC, glennjacobs commented on docs/src/getcandy/orders.md
> +@if($content ?? null)
Is `??` correct here?

2022-08-02 10:07 UTC, alecritson commented on docs/src/getcandy/orders.md
> +@if($content ?? null)
Yeah cause if the email is sent via something outside of the order notification, it won't be set potentially.

2022-08-03 09:47 UTC, glennjacobs commented on docs/src/getcandy/orders.md
> +GetCandy allows you to specific what Laravel mailers/notifications should be available for sending when you update an order's status. These are configured in the `getcandy/orders` config file and are
"GetCandy allows you to specific" < should be "specify"?

2022-08-03 09:47 UTC, glennjacobs commented on docs/src/getcandy/orders.md
> +Now when you update an order's status in the hub, you will have these mailers available if the new status is `awaiting-payment`. You can then choose the email addresses which should be sent out and a
"email addresses which should be sent out" < change to "sent to"?

2022-08-03 09:50 UTC, glennjacobs requested changes
Just some doc changes as highlighted, then good to go.

2022-08-03 10:21 UTC, glennjacobs approved these changes

2022-08-03 10:21 UTC, merged