Model Factory Trait
getcandy/getcandy pull request #416
Opened 2022-07-23 12:18 UTC by adam-code-labx

Reference to #411 
This PR will allows you to register your own models to swap and extend with the core models.

Note didn't have time to create the unit tests so will leave this one in draft for now, however tested via my own Laravel app and works as expected.

Once merged I can also create a page for the docs on this one, meanwhile see brief instructions below.

```php
ModelFactory::register([
    \GetCandy\Models\Product::class => \App\Models\Product::class,
    \GetCandy\Models\ProductOption::class => \App\Models\ProductOption::class,
]);
```

Simply define your key value pair which you can register from any of your service providers.
I have added some validation exceptions within the ModelFactory to check if the model is eloquent and the trait exists.

The PR includes adding the `InteractsWithEloquentModel` to the BaseModel class however this trait could also be added for each Candy model if you prefer.

Can extend on this later to support an array of classes, however registering from a service provider should override the implementations. Will test this further next week.

2022-07-25 06:55 UTC, alecritson commented
Considering we use Polymorphic relations which use the fully qualified name for the model, would it be better to introduce [Custom Types](https://laravel.com/docs/9.x/eloquent-relationships#custom-polymorphic-types) so we don't have to worry about the class reference being wrong?

2022-07-25 08:00 UTC, adam-code-labx commented
I would say internally for the hub you certainly could introduce custom types.

However when using the core models for the frontend we should not force the developer to use custom types. I believe checking the methods for the model on the reflection class will be enough excluding the parent class so we don’t need to worry about catching eloquent query methods.

The only addition I can think of at this stage is to support method traits. If you have any other suggestions or additional tests you would like me to create then please let me know 👍

Will create a set of unit tests today to make sure this is working with and without morph custom types and also to make sure there are no issues with dynamic relationships.

2022-07-26 10:22 UTC, glennjacobs commented
I think this is going to need a lot of testing, but the idea is good. I am going to suggest this doesn't go in the next release, but instead, we merge it into the new "develop" branch for the subsequent release.

2022-07-26 11:32 UTC, adam-code-labx commented
Ok makes sense as long as it gets merged to the new develop branch.
I will create some further tests later if required.

2022-08-11 21:02 UTC, adam-code-labx commented
I have already started to use this now for my client's project modifications.
So I will continue my customisations and create some further tests so hopefully this can then be merged to develop some point next week?

2022-08-12 12:16 UTC, alecritson commented
Hi @adam-code-labx 

After having a test with this and chatting with Glenn, there are a few gotcha's that need figuring out. He'll be back after next week so I'm going to hold off merging this until then.

2022-08-12 13:16 UTC, adam-code-labx commented
ok @alecritson 
What issues did you come across with this?

2022-08-12 13:28 UTC, glennjacobs commented
I am keen to do this properly. I know this PR is a creative potential quick fix to the problem, but I don't think it's correct.

I believe we should be using Laravel's Service Container to resolve the models from contracts (interfaces).

E.g.
```php
use GetCandy\Contracts\Models\Product as ProductInterface;
use GetCandy\Models\Product;

$this->app->bind(ProductInterface::class, Product::class);
```

And then we'd use it like


```php
use GetCandy\Contracts\Models\Product;

app(Product::class)->whereNull('something')->get();
```

That's the idea anyhow, it needs testing/proving. But it would overcome a lot of problems, including injection of models.

2022-08-12 13:45 UTC, adam-code-labx commented
Ok however if every model was to bind to an interface.
Then this would mean changing over the entire codebase to support this.

With the way I have created this model factory trait.
You can call any method and resolve from the existing model via forwardCallTo, which right now I believe is a really good workaround and I have not come across any issues so far from my side.

If you are looking to switch over the entire codebase to use contract approach then thats fine.
I was just trying to solve the problem with minimal changes to the core codebase.

Did you come across any actual errors with this? 
Thanks for your feedback @glennjacobs

2022-08-12 14:05 UTC, alecritson commented
When I was playing around with the testing, the biggest drawback seemed to be not being able to override existing methods, for example, the method `shouldBeSearchable` on the Scout trait.

I believe this is due to the usage of `__call` which will only fire if it doesn't exist in the class, in this case, it does so it doesn't trigger the check/forwarding.

2022-08-12 14:13 UTC, adam-code-labx commented
> When I was playing around with the testing, the biggest drawback seemed to be not being able to override existing methods, for example, the method `shouldBeSearchable` on the Scout trait.
> 
> I believe this is due to the usage of `__call` which will only fire if it doesn't exist in the class, in this case, it does so it doesn't trigger the check/forwarding.

Interesting we can certainly add in a check to include trait methods via forwardCallsWhen

2022-08-12 14:26 UTC, alecritson commented
I don't think it's going to work tbh, cause the `__call` method never gets fired 🤔

2022-08-12 14:35 UTC, adam-code-labx commented
Will check and make a few unit tests on this tonight

2022-08-12 20:18 UTC, adam-code-labx commented
> I don't think it's going to work tbh, cause the `__call` method never gets fired 🤔

@alecritson you are absolutely right.
Currently the trait allows you to extend any model which is what I have been doing on my side, however as you said using `__call` certainly will not override exiting methods.

This can be simply solved for example

```php
// Currently this would obviously return the original method
$product->shouldBeSearchable();

// Where as if the method name was different from the original for example this would work to forward the model call
$product->shouldBeSearchableOverride();

// The best solution here is the ability to swap the model implementation then call the overriding method
$product->swap()->shouldBeSearchable();

// Finally another way would be to prefix with an underscore then forward the the call
$product->_shouldBeSearchable();
```

I will look to implement these changes tonight then you can see if this is going to be a suitable solution.

2022-08-12 21:10 UTC, alecritson commented
I appreciate the thoughts but I still don't think it'll work, since that method is called internally by scout it will never call the proxied method and still never hit that trait 🤔

2022-08-12 21:15 UTC, adam-code-labx commented
Well I have never been one to back down from a challenge

2022-08-12 23:00 UTC, adam-code-labx commented
Solved @alecritson now overridden the instance on run time
Can you test again please. I added an additional test for shouldBeSearchable seems to work my side.

2022-08-12 23:04 UTC, adam-code-labx commented
I kept the other methods as swap is still useful especially if we want to pass in a specific model class.
Package for instance would then override the model mapping

2022-08-12 23:08 UTC, adam-code-labx commented
Strange why HasUrlsTraitTest is failing the entire test suite passes locally 🤷🏻‍♂️

2022-08-15 14:16 UTC, adam-code-labx commented
Hi @alecritson did you get chance to review my changes on this one?

2022-08-15 14:18 UTC, alecritson commented
I haven't had a chance today, will try and take a look in the next couple of days :)

2022-08-22 07:59 UTC, alecritson commented
Hey @adam-code-labx this still didn't seem to work for me...

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DemoProduct extends Model
{
    use HasFactory;

    public function shouldBeSearchable()
    {
        dd(1);
    }
}
```

```
\GetCandy\Base\ModelFactory::register([
    Product::class => DemoProduct::class,
]);
```

Ran `php artisan scout:import GetCandy\\Models\\Product`

```sh
Imported [GetCandy\Models\Product] models up to ID: 13
All [GetCandy\Models\Product] records have been imported.
```

So the `dd()` doesn't appear to have been called on the extended model, which is what I'd have expected.

2022-08-22 08:09 UTC, adam-code-labx commented
I will test further with the scout command meanwhile please try extending with GetCandy\Models\Product or BaseModel otherwise the eloquent trait will never be called it should be working as the tests pass so looks like the issue is extending.

2022-08-22 08:11 UTC, alecritson commented
@adam-code-labx Yeah sorry I didn't realise that Github Desktop didn't pull down the latest changes. The initial test I did does in fact call the the `dd`

2022-08-22 12:10 UTC, adam-code-labx commented
> Considering we use Polymorphic relations which use the fully qualified name for the model, would it be better to introduce [Custom Types](https://laravel.com/docs/9.x/eloquent-relationships#custom-polymorphic-types) so we don't have to worry about the class reference being wrong?

@alecritson I noticed the same issue when running my product migration. model_type in the media table was referencing `GetCandy\Models\Product` which means the new product thumbnail image did not show up due to my customised Product class under the App\Models namespace. I have just pushed a fix for this so no need to worry about introducing custom types. Just need to make sure the class extends the BaseModel or the current model you are overriding 👍

2022-08-24 09:06 UTC, alecritson requested changes
It's getting there and I appreciate the effort you've put into this. Just a few changes we'd like to see. Also a couple more points:

- Can we add a test to make sure when creating records with polymorphic relations, we are storing the correct class reference
- When retrieving polymorphic relations, ensure we're getting the class we expect back
- If you added a trait to your own model, can those methods be called via our Product

2022-08-24 09:31 UTC, adam-code-labx commented on docs/src/extending/models.md
> +ModelFactory::register([
Sure will rewrite the docs on this going into more detail once everything has been completed 👍

2022-08-24 09:35 UTC, adam-code-labx commented on packages/core/tests/Unit/Traits/HasUrlsTraitTest.php
> +    /** @test
This test previously failed I imagine this is before I added support for morph.
Will test again and uncomment once we know this is working.

2022-08-24 09:45 UTC, adam-code-labx commented on packages/core/src/Base/ModelFactory.php
> +class ModelFactory
@alecritson Yeah that makes sense that was people are not confused thinking this has something to do with Laravel's model factory class. Shall I setup a facade for this and register singleton interface to follow the other manifest classes?

2022-08-24 09:48 UTC, adam-code-labx commented on packages/core/src/Base/ModelFactory.php
> +class ModelFactory
Also I guess we won't need to call these methods statically as we will be using a facade

2022-08-24 09:48 UTC, alecritson commented on packages/core/src/Base/ModelFactory.php
> +class ModelFactory
Yeah that would be awesome!

2022-08-24 12:46 UTC, adam-code-labx commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
@alecritson Any of those ones better?

InteractsWithRegisteredModels
CanOverrideEloquentModel
CanExtendModel

2022-08-24 12:54 UTC, alecritson commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
`HasModelExtending` ? @glennjacobs any thoughts?

2022-08-24 12:58 UTC, adam-code-labx commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
How about something more obvious 
InteractsWithModelManifest

which is exactly what this trait is doing 😁

2022-08-24 13:30 UTC, adam-code-labx commented
@alecritson @glennjacobs 
Just pushed the ModelManifest refactor.
I will recreate the tests tonight and add the additional ones to cover morphs.

Note on morphs:
You need to make sure to define the core model for example in the media table for the image to come up you must use `GetCandy\Models\Product` It will not work by setting  this to the extended model namespace. There is probably a way to get it to work by overriding the query builder hydrate method, however I feel this may cause performance issues. So as long as we are clear in the documentation to always use the base model with morph relations then `getMorphClass` will always return the core model.

2022-08-24 18:34 UTC, adam-code-labx commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
@glennjacobs Perhaps `WithExtendedModels` or even `WithCustomModels` as this trait is on the base class so not directly related to a single model.

2022-08-24 18:37 UTC, glennjacobs commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
That kinda suggests it already has models extending it, whereas `HasModelExtending` suggests it has the functionality to allow it.

`WithModelExtending` maybe? `Has` or `With` - not sure what the normal naming convention would be?

2022-08-24 21:45 UTC, adam-code-labx commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
Personally I still prefer InteractsWith which is used a lot in the laravel framework.
So how about `InteractsWithExtendableModels` With and Has on it's own would be good if it applied to a model but as this is for the base class I feel InteractsWith would be a better fit. @alecritson what do you think?

Perhaps we should come up with 3-4 and start a poll on discord 😂
For now so I can get this finished tonight. I will go with InteractsWithExtendableModels then if we need to change this no problem.

2022-08-24 23:05 UTC, adam-code-labx commented
@glennjacobs @alecritson 
Stubbed out a few additional tests so will look to update these tomorrow night then work on the docs.

2022-08-25 06:57 UTC, alecritson commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
I went with `Has..` in my initial comment just because that's generally how they've been named in GetCandy. I'm not too sure on `InteractsWithExtendableModels` as to me it kind of implies that it interacts with extendable models which aren't itself, it doesn't really say to me that the model is extendable.

2022-08-25 08:01 UTC, adam-code-labx commented on packages/core/src/Base/BaseModel.php
> +    use InteractsWithEloquentModel;
😂 HasExtendableModels 👀

2022-08-25 22:01 UTC, adam-code-labx commented
@alecritson @glennjacobs  
This is now ready for you guys to review.

Added quite a lot of tests.
The only remaining extra morph ones to write are:

- can_get_media_thumbnail_morph_relation_when_using_extended_model
- can_get_prices_relation_when_using_extended_model
- can_return_the_correct_morph_class_when_using_enforce_morph_map

Not sure those last 3 are entirely necessary and the thumbnail one I will have to take a look at the spatie media tests for that one.  Have I have missed any other tests that you need?

Once you are happy with all this I will write the docs.

2022-08-26 06:47 UTC, alecritson commented
@adam-code-labx Still I think the trait naming is off `HasExtendableModels` suggests it has multiple models that are extended associated to it. Can we just go with `HasModelExtending` for now?

Aside from that I think it should be in a position to get it in so people can start using it, so I'd say finish up the docs then we should be in a good position.

2022-08-26 08:32 UTC, adam-code-labx commented
@alecritson You win I will rename it again 😂
I will get those last 3 tests done checked out spatie tests and looks like they don’t fake the events for the morph so should be easy to finish that one off then write out the docs.

2022-08-26 11:34 UTC, adam-code-labx commented
@glennjacobs @alecritson 
Docs updated please review let me know if you need any more changes then I will finish off on this tonight.
Starting to feel like I work with GC 🤣

2022-08-26 12:02 UTC, alecritson submitted a review, later dismissed

2022-08-26 12:02 UTC, alecritson commented on docs/src/extending/models.md
> +$newProductModel = $product->swap(
Still struggling to see the benefit of swap. Why would you not just reference your own model directly, given that GetCandy has no knowledge of the methods it provides.

2022-08-26 12:02 UTC, alecritson commented on docs/src/extending/models.md
> +All GetCandy models have been made macroable. This is a Laravel technique to allow a developer to dynamically add methods to an existing class. This is ideal for adding helpful functions for your app
Link to docs in Laravel?

2022-08-26 12:02 UTC, alecritson commented on docs/src/extending/models.md
> +You are required to extend the core model `GetCandy\Models\Cart` in order for the relationships to function correctly.
How comes this is required for the relationships to function correctly? Considering we'd be interacting with `GetCandy\Models\Cart` would they not remain intact?

2022-08-26 12:26 UTC, adam-code-labx commented on docs/src/extending/models.md
> +You are required to extend the core model `GetCandy\Models\ProductOption` in order for the relationships to function correctly.
Yes otherwise the relations will not work for example extending with BaseModel we would get
`Call to undefined relationship [thumbnail] on model [App\Models\Product].`

The new instance is correct but for the relations to work you need to extend with the model.
I can't see any problems with this as there is no need to call the App\Models\Product directly, it's just a requirement to keep all the relations working.

2022-08-26 12:30 UTC, adam-code-labx commented on docs/src/extending/models.md
> +Note: You can register model manifests to any service provider which will either extend or override your models. This of course depends on the order of your service providers.
This was to explain you can override the manifest from another provider perhaps better usage note would be within the add-on service provider?

2022-08-26 12:31 UTC, adam-code-labx commented on docs/src/extending/models.md
> +## Extendable
Models are now extendable?

2022-08-26 12:38 UTC, adam-code-labx commented on docs/src/extending/models.md
> +## Swappable
It's a separate functionality see `can_swap_registered_model_implementation`

This means at any point during the code you can swap the instance with another model. 
Which is really useful if you want to for example have several product models across you codebase perhaps calling different methods but still made of aware of the core model instance.

2022-08-26 12:39 UTC, adam-code-labx commented on docs/src/extending/models.md
> +use App\Models\Ticket;
ooops copy and paste error on that one 😁

2022-08-26 14:09 UTC, adam-code-labx commented on docs/src/extending/models.md
> +$newProductModel = $product->swap(
@alecritson I have just pushed a few changes and added a test for swap.
You were right although it allows you to swap the instance. The core model had to knowledge of the methods.
Now as you can see by my last commit this behaves exactly like the register method. 

Which is great and means we can swap the implementation from anywhere in the code and it still interacts with the core models, will update the docs tonight.

2022-08-26 17:15 UTC, adam-code-labx commented on docs/src/extending/models.md
> +## Extendable
I went with setting up sub sections main heading 
Extendable Models

2022-08-26 17:16 UTC, adam-code-labx commented on docs/src/extending/models.md
> +## Swappable
Should now be clear in the docs no longer separate functionality works with the core models to swap the extended implementation.

2022-08-26 17:18 UTC, adam-code-labx commented on docs/src/extending/models.md
> +All GetCandy models have been made macroable. This is a Laravel technique to allow a developer to dynamically add methods to an existing class. This is ideal for adding helpful functions for your app
I didn't write this one, also Macroable is not in the Laravel docs

2022-08-26 17:21 UTC, adam-code-labx commented on docs/src/extending/models.md
> +You are required to extend the core model `GetCandy\Models\Cart` in order for the relationships to function correctly.
Few possible options going forward would be ReflectionClass or possibly PHP 8 attribute
something like `#[extends(model: 'Product')]`

I think leave it as it is right now.

2022-08-26 17:22 UTC, adam-code-labx commented on docs/src/extending/models.md
> +    use SearchableTrait;
Updated docs you can use either trait or class

2022-08-26 17:22 UTC, adam-code-labx commented on docs/src/extending/models.md
> +    use HasAddresses;
See the trait below

2022-08-26 17:24 UTC, adam-code-labx commented
@glennjacobs @alecritson 
Ready for another review 👍

2022-08-30 10:23 UTC, adam-code-labx commented
@glennjacobs @alecritson 
Any chance with getting this merged into develop this week?
Tried to request you both for review looks like I can only request one of you 😂

2022-09-02 07:08 UTC, alecritson commented
Thanks @adam-code-labx @glennjacobs Just needs to do the review to get sign off and then we'll be good I hope.

2022-09-04 11:58 UTC, adam-code-labx commented
@glennjacobs @alecritson  
After continuing to override more models. I came across an issue today with model observer events.
Eloquent uses static::class for events which means in this case events could not fire if you have registered a custom model in the App namespace.

Solved this in the last few commits, also Activity logger was showing the logs but renderers returns empty array so solved this by checking for the base class. So all good now.

2022-09-05 08:14 UTC, glennjacobs approved these changes

2022-09-05 08:14 UTC, merged