Change slugs to use underscore
getcandy/getcandy pull request #83
Opened 2022-01-21 22:17 UTC by itcyborg

Update how handle is generated when creating an attribute. This is to prevent issues when parsing the attributes in javascript without adding additional mapping using php.
case : suppose we want to add an attribute named "warranty information", the handle generated will be 'warranty-information'. this commit attempts to fix this by replacing '-' with '_'

2022-01-27 16:02 UTC, itcyborg commented
The snake helper does not change the delimiter if it already exists.
![image](https://user-images.githubusercontent.com/22530253/151396194-04a80b60-f8d1-4bb6-b2d2-3040f725f673.png)

2022-01-27 16:03 UTC, itcyborg commented
The suggestion can work if the words are separated by spaces.

2022-01-27 21:42 UTC, glennjacobs commented
It's likely we may want to use this style of "slugification" in other parts of the system or even addons down the line. 

I suggest we look to add our own string helper to avoid duplication.

e.g. 

```php
      Str::macro('snakeSlug', function (string $value) {
            Str::slug($value, '_')
      });
```

2022-01-28 08:53 UTC, alecritson commented
What if it was named something like:

```php
Str::handle($handle);
```

2022-01-28 08:55 UTC, itcyborg commented
> What if it was named something like:
> 
> ```
> Str::handle($handle);
> ```

This would make more sense.

2022-01-28 08:56 UTC, glennjacobs commented
Yeah, that name sounds good.

2022-01-30 12:00 UTC, alecritson requested changes
I appreciate your effort on this and it is looking good. 

Can we get some basic tests in for the macro to make sure it's returning what we expect based on a bunch of different strings that could be passed.

2022-01-30 12:00 UTC, alecritson commented on packages/admin/src/AdminHubServiceProvider.php
> +        Str::macro('handle', function ($string) {
I feel like this should be registered in the core. Other areas of GetCandy will likely benefit from this, not just admin hub code.

2022-01-30 15:50 UTC, itcyborg commented on packages/admin/src/AdminHubServiceProvider.php
> +        Str::macro('handle', function ($string) {
I have updated as requested. The helper is now in getcandy core package. I've also added some unit test for the helper function. Hope this is well. let me know if further changes are required.

2022-01-31 11:58 UTC, alecritson commented
Thanks for sorting @itcyborg I'll get this merged ready for the upcoming release!

2022-01-31 11:58 UTC, alecritson approved these changes

2022-01-31 11:58 UTC, merged